USE smart_transportation;

ANALYZE TABLE tlc_trips
COMPUTE STATISTICS;

ANALYZE TABLE tlc_trips
COMPUTE STATISTICS FOR COLUMNS;

ANALYZE TABLE tlc_daily_summary
COMPUTE STATISTICS;

ANALYZE TABLE tlc_daily_summary
COMPUTE STATISTICS FOR COLUMNS;

ANALYZE TABLE tlc_hourly_summary
COMPUTE STATISTICS;

ANALYZE TABLE tlc_hourly_summary
COMPUTE STATISTICS FOR COLUMNS;

ANALYZE TABLE tlc_daily_hourly_summary
COMPUTE STATISTICS;

ANALYZE TABLE tlc_daily_hourly_summary
COMPUTE STATISTICS FOR COLUMNS;